import { z } from "zod";
import { eq } from "drizzle-orm";
import type { Db } from "../../db/client.ts";
import { servers } from "../../db/schema/inventory.ts";
import { writeAudit } from "../../db/audit-writer.ts";
import { errValidation, errNotFound } from "../../kernel/errors.ts";
import { readHostKeyFingerprint } from "../../../shared/preflight.ts";
import { isMasterRole } from "../../../shared/enums.ts";

// WHAT A PERSON SAYS WHEN A MACHINE WAS REBUILT, and the only way the two numbers this manager
// records about a machine's operating system are ever replaced.
//
// Those two numbers are the sshd host key pinned on the row (preflightJson.hostKey, offered to the
// transport by executor/context.ts so key exchange itself refuses a machine that disagrees) and
// /etc/machine-id (servers.machine_id, verified by executor/attest.ts before anything destructive
// runs). Both are recorded on first contact and never overwritten afterwards, because a value
// rewritten on every connect is a record of the last connection rather than a claim about the
// machine, and such a record can never disagree with anything.
//
// SO A MACHINE THAT ANSWERS WITH NEW ONES IS REFUSED, and it is refused for two reasons that no
// manager can tell apart: the operator reinstalled it, or somebody else is answering at its
// address. The difference is not a reading anything here could take — it is a fact only a person
// holds. This act is where that person states it, which is why it is a statement about a specific
// machine and not a confirmation:
//
//   - THE PERSON STATES THE NUMBER, and the number has to come off the machine. The row is pinned on
//     what they typed, so the next run still refuses everything that presents anything else, and a
//     wrong statement moves the refusal rather than removing it. A yes/no confirmation would be a
//     default with extra clicks — this is the one shape where the person has to go and look.
//   - IT REACHES NO MACHINE. Nothing here connects anywhere: it rewrites what this manager records
//     and leaves the machine to prove the claim on the next run, at the door, before a credential is
//     offered to it.
//   - IT IS AUDITED WITH BOTH NUMBERS, so the trail says which identity was replaced by which and by
//     whom, which is the only thing a later reader can judge the statement on.
//
// THE MACHINE-ID GOES WITH THE HOST KEY because a rebuild replaces both, and they are one fact.
// Restating the host key alone opens the door and then stops the same run one step later, at the
// machine-id check — a repair that gets a person half way is a dead end with a longer path to it.
// Dropping it back to NULL restores the first-contact shape: the next run records the machine-id of
// whatever machine presents the stated host key, and that machine presents the stated key or it
// gets no session at all.
//
// BUT THE TWO NUMBERS DO NOT ALWAYS MOVE TOGETHER, and this act is the only thing that reaches the
// case where one moves alone. /etc/machine-id is regenerated by ordinary administration —
// `systemd-machine-id-setup` after a virtual machine is cloned, or removing the file to stop two
// machines sharing one DHCP lease — while the host keys under /etc/ssh stand untouched. Such a
// machine opens every door and is refused one step later, by attestMachineId, on every run kind that
// attests it. NOTHING ELSE IN THIS MANAGER CLEARS THAT COLUMN and nothing else should:
// executor/attest.ts writes it exactly once, where it is NULL, and never overwrites it, because a
// value rewritten on every connect is a record of the last connection rather than a claim about the
// machine. So the statement has to reach that machine too, and it does — a person who states the
// fingerprint ALREADY pinned is saying they went and looked and the host key is the recorded one,
// which is the whole of what this manager can be told about a machine whose sshd did not change.
//
// THAT HALF ADMITS NO MACHINE THE PIN WOULD NOT ADMIT ALREADY. The host key is what decides which
// machine gets a session, and forgetting a machine-id moves none of it: whoever answers the address
// still presents the pinned key or gets nothing. It is the weaker half of the act and safe for
// exactly that reason, which is why the master gets this half while the other one stays refused for
// it — the master's pin is configuration and its machine-id is not, so this is the only route back
// for a control host that was re-imaged while its manager database survived.
//
// A ROW PINNING NOTHING CARRIES NO MACHINE-ID EITHER, so the refusal below covers both numbers with
// one sentence: a machine-id is only ever recorded over a session (executor/attest.ts), and opening
// one records the host key first where the row holds none (executor/context.ts).

/** WHAT A PERSON STATES. One field, because the fingerprint is the whole statement — a machine
 *  matches it or it does not — and strict, so a body carrying anything else is refused rather than
 *  quietly narrowed to the part this act acts on. */
export const RestateMachineIdentityInput = z.object({
  /** The fingerprint the machine presents now, in the form `ssh-keygen -lf` prints. */
  hostKeyFingerprint: z.string().min(1),
}).strict();
export type RestateMachineIdentityInput = z.infer<typeof RestateMachineIdentityInput>;

/**
 * Pin the host key a person states for a machine and forget the machine-id recorded beside it.
 *
 * Synchronous, because it writes two rows of this database and reaches neither a machine nor the
 * credential store: the key this manager holds for the machine stays sealed exactly as it is, and
 * the door offers it first on the next run — a rebuilt machine refuses it, which is the case
 * openDoor falls back to the machine account's password for (runs/defs/manager-key.kit.ts).
 *
 * TWO HALVES, and which of them a statement performs is decided by the number itself rather than by
 * a second field: a fingerprint that DIFFERS from the pin says the sshd was rebuilt and moves both
 * numbers, and the fingerprint ALREADY pinned says the person went to the machine and found its host
 * key standing, which moves the recorded machine-id alone. Both are one statement about one machine,
 * so both write through this one function and one audit entry.
 *
 * FOUR REFUSALS, each of them a different thing being wrong:
 *   - a row pinning nothing has no identity to restate, and the next run records what it meets;
 *   - a fingerprint of the wrong shape can never be presented by any machine, so pinning it would
 *     replace a refusal that names a real machine with one that names nothing;
 *   - a fingerprint that differs from the pin, on a machine carrying the master part, whose pin
 *     comes from its own deployment configuration and is re-read on every boot (boot/seed-master.ts)
 *     — a value stated here would not survive one, and the machine-id half stays open to it;
 *   - and the statement that would move neither number: the pinned fingerprint on a row that carries
 *     no recorded machine-id, which would report a repair that repaired nothing.
 */
export function restateMachineIdentity(db: Db, actor: string, id: string, input: RestateMachineIdentityInput): void {
  const row = db.select().from(servers).where(eq(servers.id, id)).get();
  if (!row) throw errNotFound(`server ${id} not found`);
  const pf = (row.preflightJson as Record<string, unknown> | null) ?? {};
  const pinned = typeof pf.hostKey === "string" ? pf.hostKey : undefined;
  if (!pinned) {
    throw errValidation(
      `no host key is recorded for ${row.name}, so nothing about its identity is in the way: the next run records the ` +
      `key the machine presents and pins every later session on it.`,
    );
  }
  const stated = readHostKeyFingerprint(input.hostKeyFingerprint);
  if (!stated) {
    throw errValidation(
      `"${input.hostKeyFingerprint}" is not a host-key fingerprint — a machine presents SHA256: followed by 43 base64 ` +
      `characters, which is the field \`ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub\` prints between the key size ` +
      `and the comment.`,
    );
  }
  if (stated !== pinned && isMasterRole(row.role)) {
    throw errValidation(
      `${row.name} holds the master role, and this manager pins its host key from its own deployment configuration ` +
      `(MASTER_SSH_HOST_KEY_FP, or the file behind it), which is read again on every boot — state the new fingerprint there. ` +
      `What this act can still do for it is forget the recorded /etc/machine-id, which is stated by giving the ` +
      `fingerprint the machine presents now when that is the one already pinned.`,
    );
  }
  if (stated === pinned && row.machineId === null) {
    throw errValidation(
      `${stated} is already what this manager has pinned for ${row.name} and no /etc/machine-id is recorded beside it, ` +
      `so neither number this manager holds about the machine is in the way — the run's own line names what is.`,
    );
  }
  db.update(servers).set({ preflightJson: { ...pf, hostKey: stated }, machineId: null }).where(eq(servers.id, id)).run();
  writeAudit(db, {
    actor,
    action: "server.machine_identity_restated",
    targetKind: "server",
    targetId: id,
    detail: { name: row.name, hostKeyWas: pinned, hostKeyNow: stated, machineIdDropped: row.machineId },
  });
}
